[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk
debug_tool = picoprobe
build_src_flags = -O0
upload_protocol = picoprobe
monitor_speed = 115200
build_flags = 
    -DPICOJSON_USE_ASSERT
    # -D UNITY_INCLUDE_CONFIG_H
    -I test/unity_config
    -I include 
    -I include/joysticks 
    -I include/leds
    -I include/uart
    -I include/config
    -I include/inputEmulators
    -I include/inputHandlers
    -I include/keypadButtons
test_framework = unity
test_build_src = true
# test_filter = 
